using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using Frends.Files.LocalBackup.Definitions;
using Frends.Files.LocalBackup.Helpers;

namespace Frends.Files.LocalBackup
{
    /// <summary>
    /// Files task.
    /// </summary>
    public static class Files
    {
        /// <summary>
        /// Create a local backup. Optionally task can create new subdirectories for backups and delete old backup directories.
        /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.Files.LocalBackup)
        /// </summary>
        /// <param name="input">Input parameters</param>
        /// <param name="options">Additional task options.</param>
        /// <param name="cancellationToken">Token to stop task. This is generated by Frends.</param>
        /// <returns>Result object { bool Success, string Directory, int FileCountInBackup, List&lt;string&gt; Backups, List&lt;string&gt; Cleanups, object Error { string Message, Exception AdditionalInfo } }</returns>
        public static Result LocalBackup([PropertyTab] Input input, [PropertyTab] Options options, CancellationToken cancellationToken)
        {
            try
            {
                ValidationHandler.Run(input, options);
                cancellationToken.ThrowIfCancellationRequested();

                var timestampString = DateTime.UtcNow.ToString("yyyy-MM-dd_HH_mm_ss");
                var backupDirectory = input.CreateSubdirectories
                    ? Path.Combine(input.BackupDirectory, $"{timestampString}-{input.TaskExecutionId}")
                    : input.BackupDirectory;

                var (directory, backup) = CreateBackup(input, backupDirectory, cancellationToken);

                var cleanup = input.Cleanup ? CleanUp(input, input.BackupDirectory, cancellationToken) : null;

                return new Result(true, directory: directory, backups: backup, cleanups: cleanup);
            }
            catch (Exception exception)
            {
                return exception.Handle(options);
            }
        }

        private static Tuple<string, List<string>> CreateBackup(Input input, string backupDirectory, CancellationToken cancellationToken)
        {
            var result = new List<string>();

            Directory.CreateDirectory(backupDirectory);
            string[] files;

            if (input.FilePaths != null)
            {
                files = ConvertObjectToStringArray(input.FilePaths);
                foreach (string file in files)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    if (File.Exists(file))
                    {
                        var backupFile = Path.Combine(backupDirectory, Path.GetFileName(file));
                        File.Copy(file, backupFile, true);
                        result.Add($"Backup complete: {file} to {backupFile}");
                    }
                }
            }
            else
            {
                files = Directory.GetFiles(input.SourceDirectory);
                foreach (string file in files)
                {
                    cancellationToken.ThrowIfCancellationRequested();

                    if (!FilesHandler.FileMatchesMask(Path.GetFileName(file), input.SourceFile)) continue;
                    var backupFile = Path.Combine(backupDirectory, Path.GetFileName(file));
                    File.Copy(file, backupFile, true);
                    result.Add($"Backup complete: {file} to {backupFile}");
                }
            }

            if (Directory.GetFiles(backupDirectory).Length == 0 && Directory.GetDirectories(backupDirectory).Length == 0)
            {
                Directory.Delete(backupDirectory, false);
                return new Tuple<string, List<string>>("No source files present to backup.", []);
            }

            return new Tuple<string, List<string>>(backupDirectory, result);
        }

        private static List<string> CleanUp(Input input, string backupDirectory, CancellationToken cancellationToken)
        {
            var result = new List<string>();

            if (!input.CreateSubdirectories)
            {
                if (Directory.Exists(backupDirectory))
                {
                    var directories = Directory.GetDirectories(backupDirectory);

                    foreach (var dir in directories.Where(d => Directory.GetLastWriteTime(d) < DateTime.Now.AddDays(-input.DaysOlder)))
                    {
                        Directory.Delete(dir, true);
                        result.Add($"{dir} deleted.");
                    }

                    var files = Directory.GetFiles(backupDirectory);
                    foreach (var file in files.Where(f => File.GetLastWriteTime(f) < DateTime.Now.AddDays(-input.DaysOlder)))
                    {
                        File.Delete(file);
                        result.Add($"{file} deleted.");
                    }
                }
            }
            else
            {
                if (input.DaysOlder < 0)
                {
                    throw new ArgumentException("Days older cannot be a negative number", nameof(input.DaysOlder));
                }

                var directories = Directory.GetDirectories(backupDirectory).Where(dirName => ShouldBeCleanedUp(dirName, input));

                foreach (var dir in directories)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    Directory.Delete(dir, true);
                    result.Add($"{dir} deleted.");
                }
            }

            return result;
        }

        private static bool ShouldBeCleanedUp(string dirPath, Input input)
        {
            const string timestampPattern = "yyyy-MM-dd_HH_mm_ss";
            var dirNamePatternLength = timestampPattern.Length + input.TaskExecutionId.Length + 1; // Add one to the Length because of '-' character which separates the timestamp and guid.
            var dirName = Path.GetFileName(dirPath) ?? string.Empty;

            if (dirName.Length == dirNamePatternLength)
            {
                var timestampPart = dirName.Substring(0, timestampPattern.Length);

                if (DateTime.TryParseExact(timestampPart, timestampPattern, CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime timeStamp))
                {
                    return timeStamp < DateTime.UtcNow.AddDays(-input.DaysOlder);
                }
            }

            return File.GetCreationTimeUtc(dirPath) < DateTime.UtcNow.AddDays(-input.DaysOlder);
        }

        private static string[] ConvertObjectToStringArray(object objectArray)
        {
            if (!objectArray.GetType().IsArray)
                throw new ArgumentException($"Invalid type for parameter FilePaths. Expected array but was {objectArray.GetType()}");

            var res = objectArray as object[];
            return res?.OfType<string>().ToArray();
        }
    }
}
