name: LocalBackup_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.Files.LocalBackup/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.Files.LocalBackup
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}